### ISSUE TITLE
Empty string search is only filtered in frontend

### ISSUE THREAD

**Issue by KDercksen** [dopefishh/cloogle#19]
Communicating directly with CloogleServer allows for searching on the empty string, while the PHP frontend filters this as being illegal. For continuity's sake, shouldn't this be responded to with a non-zero return code response? Or do you reckon it's up to the client to handle this?

**Comment by KDercksen** [comment]
There is a slight complexity with this I just thought of; an empty string should be allowed when the modules field is supplied in the request. This allows for listing all functions of a certain (set of) modules, and I wouldn't like to lose that functionality.

It's probably easier to just allow searching for the empty string in the backend and filter it at client level as necessary.

**Comment by camilstaps** [comment]
I think the reason the frontend filters this is because before (when we used a PHP backend with a regex search), searching for the empty string would yield all results and that would be slow. @dopefishh is this correct?

Now, such a search still yields all results (because &lambda; is a substring of every string), but the backend is considerably faster. Also, only the first 15 results will be returned by the backend ever, so there is no risk of DoS attacks with this.

I'm fine with removing the restriction altogether. I don't see a reason for moving the restriction into the backend because there are no problems with searching for the empty string. At the moment it is just a feature for the frontend user to let him understand why what he does doesn't make any sense.

Anyway, once #16 is implemented we will accept requests without the name field. Then we have the question what to do with the empty request.

**Comment by camilstaps** [comment]
I just tried

```bash
time for i in $(seq 1 115); do echo "{\"name\":\"\",\"unify\":\"\",\"page\":$i}" | netcat cloogle.org 31215 >/dev/null; done
```

It takes a little more than 1s to list all functions. If people want to DoS there are better ways.

**Comment by KDercksen** [comment]
With that performance I see no reason to filter except for letting the user know he's doing something stupid.

The empty request is another problem, but I guess we don't have to discuss that here yet.
