### ISSUE TITLE
Object IO not in Clean 2.4 standard search libraries

### ISSUE THREAD

**Issue by peterachten** [dopefishh/cloogle#71]
I noticed that Object IO is not present in the search libraries of Clean 2.4 standard search. Can it be added? It is complicated a little by the different kind of users:
(a) API users should only search within the exported StdXXX.dcl modules
(b) Object IO implementers should search within the other modules as well

**Comment by dopefishh** [comment]
ObjectIO should definitly be added.
The same thing should be done with iTasks. _Framework should not be enabled by default.

**Comment by camilstaps** [comment]
Plan:

- The `TypeDB` type should get a field `modulemap :: Map (Library, Module) ModuleInfo` with `:: ModuleInfo = { is_core :: Bool }`.
- `builddb.icl` should be adapted to fill the module map. The `CLI` type should be changed so that files matching some pattern can be marked as core. For example, `libs :: [(String, [String] -> Bool)]` where the second element would e.g. give True for `["ObjectIO", "toolbar"]`.
- In `Cloogle.dcl`, the `Request` type should get a new field `include_core`. While we're at it, the second element of `libraries` (to include language builtins) could get its own field.

@dopefishh is it only iTasks._Framework?

**Comment by dopefishh** [comment]
@camilstaps for iTasks you preferably only want the modules that are imported by the top level module iTasks. All the rest is internal and not supposed to be public for non-implementers. This is not the case for all libraries.
