### ISSUE TITLE
update the libraries

### ISSUE THREAD

**Issue by dopefishh** [dopefishh/cloogle#77]
There is a new release system for all the libraries. This allows for updating libraries separately.
ftp://ftp.cs.ru.nl/pub/Clean/builds/ contains all these builds and there are symlinks for the latest versions.

In this way we can separate the different libraries. Moreover, the layout has changed for the user. For example clean-platform is no longer a submodule of iTasks. clean-platform bundles now come per OS, thus there are no more OS-Independant, OS-Posix folders anymore. Even more so, Sapl is a now living in `$CLEAN_HOME/lib/Sapl` and the same for Graphcopy and friends.

**Comment by camilstaps** [comment]
The new release system is a terrible change that does not solve the problem which really needs to be solved; (versioned) package management.

Ideally, we would not only store library and module but also its version number. Then we could simply index all versions of the libraries and allow the user to select an older version. With the nightly builds, this is impossible because (1) it is not possible to download an old release, (2) there are too many dates to store / have the user select and (3) there may be a 'new' nightly build with nothing changed.

But that's not a problem with cloogle. The nightly builds make it impossible for people to compare their code because they will be working on different versions, etc. Always offering the latest versions on cloogle is an arbitrary choice and will only be useful to the very few who update their system every day because they need to work on the latest system. Most people download the stable release, so at least for those libraries I wouldn't want to offer the nightly builds. For iTasks and clean-platform: yes, we could offer the latest builds, but that always remains an arbitrary choice and will keep annoying users until the release system is revisited properly.

We could invest time in that but I think it's better to develop a usable workflow first.

**Comment by dopefishh** [comment]
Maybe we should just update clean-platform and iTasks, thus leave the base system as is. There are no stable versions of those and it is really ennoying to have to grep the source to find my favourite functions.

**Comment by camilstaps** [comment]
Yes, maybe, but then we need to rebuild *and* clean the cache with every new commit. I talked to Bas today and he was interested in versioning the libraries, so maybe we can wait for that instead? Or if you can adapt the dockerfile to get the latest sources (in both the backend and src/view.php) then I can setup something to rebuild every night.

**Comment by camilstaps** [comment]
Is this done now, since https://github.com/dopefishh/cloogle/commit/356bcd5bd596d1505749d23160877801f096475e?

**Comment by camilstaps** [comment]
@dopefishh I had to change index.html because clean-platform was renamed to Platform; do similar things need to be done for iTasks?

**Comment by dopefishh** [comment]
I've changed index.html and added gast in #85. However, this doesn't work, the advanced dos protection is not working

**Comment by dopefishh** [comment]
this is done and tested, I'll merge #85
